spring:
  ai:
    model:
      embedding: ollama
    ollama:
      embedding:
        options:
          model: nomic-embed-text
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        enabled: false
    openfeign:
      circuitbreaker:
        enabled: false

eureka:
  client:
    enabled: false


