
spring:
  profiles:
    active: dev
  application:
    name: SpringAIDemo
  config:
    import:
      - nacos:common-config.yaml
      - nacos:springai-config.yaml
      - nacos:springai-config-${spring.profiles.active}.yaml

  # ① MySQL 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/springai?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456      # ← ⚠️ 改成你自己的真实密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  ai:
    # ② Ollama 模型
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:7b

    # ③ 自动建对话记忆表
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: 123456
      config:
        server-addr: localhost:8848
        username: nacos
        password: 123456
    openfeign:
      circuitbreaker:
        enabled: true

logging:
  level:
    org.springframework.ai.model.tool: DEBUG
    org.springframework.ai.tool: DEBUG
server:
  port: 8989
#测试用
management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,circuitbreakerevents
#结束
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5  # 看最近 5 次
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3 #半开时放 3 个试探
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9898/eureka




